# Generated by Django 6.0.3 on 2026-03-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=9, unique=True)),
                ('email_institucional', models.EmailField(max_length=254, unique=True)),
                ('carrera', models.CharField(choices=[('COMP', 'Ingeniería en Computación'), ('MECA', 'Ingeniería Mecánica'), ('INDU', 'Ingeniería Industrial'), ('ELEC', 'Ingeniería Eléctrica Electrónica'), ('OTRA', 'Otra (Especificar)')], max_length=10)),
                ('otra_carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('carta_motivos', models.TextField()),
            ],
        ),
    ]
